/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: v2
 */
import type { Context, Env } from 'hono'

import {
	GetContentItemByIdParams,
	GetContentItemByPathParams,
	GetContentItemsParams,
	GetContentParams,
	GetMediaItemByIdParams,
	GetMediaItemByPathParams,
	GetMediaItemsParams,
	GetMediaParams
} from './umbraco.schemas'

export type GetContentContext<E extends Env = any> = Context<
	E,
	'/umbraco/delivery/api/v2/content',
	{ in: { query: GetContentParams }; out: { query: GetContentParams } }
>
export type GetContentItemByPathContext<E extends Env = any> = Context<
	E,
	'/umbraco/delivery/api/v2/content/item/:path',
	{
		in: {
			param: {
				path: string
			}
			query: GetContentItemByPathParams
		}
		out: {
			param: {
				path: string
			}
			query: GetContentItemByPathParams
		}
	}
>
export type GetContentItemByIdContext<E extends Env = any> = Context<
	E,
	'/umbraco/delivery/api/v2/content/item/:id',
	{
		in: {
			param: {
				id: string
			}
			query: GetContentItemByIdParams
		}
		out: {
			param: {
				id: string
			}
			query: GetContentItemByIdParams
		}
	}
>
export type GetContentItemsContext<E extends Env = any> = Context<
	E,
	'/umbraco/delivery/api/v2/content/items',
	{ in: { query: GetContentItemsParams }; out: { query: GetContentItemsParams } }
>
export type GetMediaContext<E extends Env = any> = Context<
	E,
	'/umbraco/delivery/api/v2/media',
	{ in: { query: GetMediaParams }; out: { query: GetMediaParams } }
>
export type GetMediaItemByPathContext<E extends Env = any> = Context<
	E,
	'/umbraco/delivery/api/v2/media/item/:path',
	{
		in: {
			param: {
				path: string
			}
			query: GetMediaItemByPathParams
		}
		out: {
			param: {
				path: string
			}
			query: GetMediaItemByPathParams
		}
	}
>
export type GetMediaItemByIdContext<E extends Env = any> = Context<
	E,
	'/umbraco/delivery/api/v2/media/item/:id',
	{
		in: {
			param: {
				id: string
			}
			query: GetMediaItemByIdParams
		}
		out: {
			param: {
				id: string
			}
			query: GetMediaItemByIdParams
		}
	}
>
export type GetMediaItemsContext<E extends Env = any> = Context<
	E,
	'/umbraco/delivery/api/v2/media/items',
	{ in: { query: GetMediaItemsParams }; out: { query: GetMediaItemsParams } }
>
export type GetNavigationItemsContext<E extends Env = any> = Context<E, '/umbraco/delivery/api/v2/navigation/items'>
export type GetTranslationsItemsContext<E extends Env = any> = Context<E, '/umbraco/delivery/api/v2/translations/items'>
