/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: v2
 */
export type IApiContentResponseModelProperties = { [key: string]: unknown | null }

export type IApiContentResponseModelCultures = { [key: string]: IApiContentRouteModel }

export interface IApiContentResponseModel {
	readonly id?: string
	readonly contentType?: string
	readonly properties?: IApiContentResponseModelProperties
	/** @nullable */
	readonly name?: string | null
	readonly createDate?: string
	readonly updateDate?: string
	route?: IApiContentRouteModel
	readonly cultures?: IApiContentResponseModelCultures
}

export interface IApiContentRouteModel {
	readonly path?: string
	startItem?: IApiContentStartItemModel
}

export interface IApiContentStartItemModel {
	readonly id?: string
	readonly path?: string
}

export type IApiMediaWithCropsResponseModelProperties = { [key: string]: unknown | null }

export interface IApiMediaWithCropsResponseModel {
	readonly id?: string
	readonly name?: string
	readonly mediaType?: string
	readonly url?: string
	/** @nullable */
	readonly extension?: string | null
	/** @nullable */
	readonly width?: number | null
	/** @nullable */
	readonly height?: number | null
	/** @nullable */
	readonly bytes?: number | null
	readonly properties?: IApiMediaWithCropsResponseModelProperties
	focalPoint?: ImageFocalPointModel
	/** @nullable */
	readonly crops?: readonly ImageCropModel[] | null
	readonly path?: string
	readonly createDate?: string
	readonly updateDate?: string
}

export interface ImageCropCoordinatesModel {
	x1?: number
	y1?: number
	x2?: number
	y2?: number
}

export interface ImageCropModel {
	/** @nullable */
	alias?: string | null
	width?: number
	height?: number
	coordinates?: ImageCropCoordinatesModel
}

export interface ImageFocalPointModel {
	left?: number
	top?: number
}

export interface Locale {
	isDefault?: boolean
	label?: string
	isoCode?: string
	defaultPath?: string
	talentCommunityLink?: string
	navigation?: NavigationItem[]
}

export type NavigationApiResponseLocales = { [key: string]: Locale }

export interface NavigationApiResponse {
	locales?: NavigationApiResponseLocales
}

export interface NavigationChild {
	id?: string
	title?: string
	path?: string
}

export interface NavigationItem {
	id?: string
	title?: string
	path?: string
	children?: NavigationChild[]
}

export interface PagedIApiContentResponseModel {
	total: number
	items: IApiContentResponseModel[]
}

export interface PagedIApiMediaWithCropsResponseModel {
	total: number
	items: IApiMediaWithCropsResponseModel[]
}

export interface ProblemDetails {
	/** @nullable */
	type?: string | null
	/** @nullable */
	title?: string | null
	/** @nullable */
	status?: number | null
	/** @nullable */
	detail?: string | null
	/** @nullable */
	instance?: string | null
	[key: string]: unknown
}

export interface TranslationApiDictionaryItem {
	name?: string
	[key: string]: unknown
}

export interface TranslationApiResponse {
	languages?: string[]
	dictionaries?: TranslationApiDictionaryItem[]
}

export type GetContentParams = {
	/**
	 * Specifies the content items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	fetch?: string
	/**
	 * Defines how to filter the fetched content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	filter?: string[]
	/**
	 * Defines how to sort the found content items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	sort?: string[]
	/**
	 * Specifies the number of found content items to skip. Use this to control pagination of the response.
	 */
	skip?: number
	/**
	 * Specifies the number of found content items to take. Use this to control pagination of the response.
	 */
	take?: number
	/**
	 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	expand?: string
	/**
	 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	fields?: string
}

export type GetContentItemByPathParams = {
	/**
	 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	expand?: string
	/**
	 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	fields?: string
}

export type GetContentItemByIdParams = {
	/**
	 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	expand?: string
	/**
	 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	fields?: string
}

export type GetContentItemsParams = {
	id?: string[]
	/**
	 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	expand?: string
	/**
	 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#query-parameters) for more details on this.
	 */
	fields?: string
}

export type GetMediaParams = {
	/**
	 * Specifies the media items to fetch. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	fetch?: string
	/**
	 * Defines how to filter the fetched media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	filter?: string[]
	/**
	 * Defines how to sort the found media items. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	sort?: string[]
	/**
	 * Specifies the number of found media items to skip. Use this to control pagination of the response.
	 */
	skip?: number
	/**
	 * Specifies the number of found media items to take. Use this to control pagination of the response.
	 */
	take?: number
	/**
	 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	expand?: string
	/**
	 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	fields?: string
}

export type GetMediaItemByPathParams = {
	/**
	 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	expand?: string
	/**
	 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	fields?: string
}

export type GetMediaItemByIdParams = {
	/**
	 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	expand?: string
	/**
	 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	fields?: string
}

export type GetMediaItemsParams = {
	id?: string[]
	/**
	 * Defines the properties that should be expanded in the response. Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	expand?: string
	/**
	 * Explicitly defines which properties should be included in the response (by default all properties are included). Refer to [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/media-delivery-api#query-parameters) for more details on this.
	 */
	fields?: string
}
