/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { NavigationApiResponse, ProblemDetails } from '.././schemas'

import { UmbracoClient, UmbracoClientOptions } from '../../clients/umbraco-client'

export type getUmbracoDeliveryApiV2NavigationItemsResponse200 = {
	data: NavigationApiResponse
	status: 200
}

export type getUmbracoDeliveryApiV2NavigationItemsResponse401 = {
	data: ProblemDetails
	status: 401
}

export type getUmbracoDeliveryApiV2NavigationItemsResponseComposite =
	| getUmbracoDeliveryApiV2NavigationItemsResponse200
	| getUmbracoDeliveryApiV2NavigationItemsResponse401

export type getUmbracoDeliveryApiV2NavigationItemsResponse =
	getUmbracoDeliveryApiV2NavigationItemsResponseComposite & {
		headers: Headers
	}

export const getGetUmbracoDeliveryApiV2NavigationItemsUrl = () => {
	return '/umbraco/delivery/api/v2/navigation/items'
}

export const getUmbracoDeliveryApiV2NavigationItems = async (
	options?: RequestInit
): Promise<getUmbracoDeliveryApiV2NavigationItemsResponse> => {
	return UmbracoClient<getUmbracoDeliveryApiV2NavigationItemsResponse>(
		getGetUmbracoDeliveryApiV2NavigationItemsUrl(),
		{
			...(options as UmbracoClientOptions),
			method: 'GET'
		}
	)
}
