/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ProblemDetails, TranslationApiResponse } from '.././schemas'

import { UmbracoClient, UmbracoClientOptions } from '../../clients/umbraco-client'

export type getUmbracoDeliveryApiV2TranslationsItemsResponse200 = {
	data: TranslationApiResponse
	status: 200
}

export type getUmbracoDeliveryApiV2TranslationsItemsResponse401 = {
	data: ProblemDetails
	status: 401
}

export type getUmbracoDeliveryApiV2TranslationsItemsResponseComposite =
	| getUmbracoDeliveryApiV2TranslationsItemsResponse200
	| getUmbracoDeliveryApiV2TranslationsItemsResponse401

export type getUmbracoDeliveryApiV2TranslationsItemsResponse =
	getUmbracoDeliveryApiV2TranslationsItemsResponseComposite & {
		headers: Headers
	}

export const getGetUmbracoDeliveryApiV2TranslationsItemsUrl = () => {
	return '/umbraco/delivery/api/v2/translations/items'
}

export const getUmbracoDeliveryApiV2TranslationsItems = async (
	options?: RequestInit
): Promise<getUmbracoDeliveryApiV2TranslationsItemsResponse> => {
	return UmbracoClient<getUmbracoDeliveryApiV2TranslationsItemsResponse>(
		getGetUmbracoDeliveryApiV2TranslationsItemsUrl(),
		{
			...(options as UmbracoClientOptions),
			method: 'GET'
		}
	)
}
