/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ISearchResult } from './iSearchResult';
import type { IQueryBuilder } from './iQueryBuilder';
import type { SearchResult } from './searchResult';

export interface ExamineSearchResults {
  readonly hasResults?: boolean;
  readonly baseSearchResults?: readonly ISearchResult[];
  readonly searchPhrase?: string;
  queryBuilder?: IQueryBuilder;
  readonly rawQuery?: string;
  readonly totalResults?: number;
  searchResults?: SearchResult[];
  readonly errorMessages?: readonly string[];
  readonly hasErrors?: boolean;
}
