/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */

export type IndexType = typeof IndexType[keyof typeof IndexType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexType = {
  All: 'All',
  Content: 'Content',
  Media: 'Media',
} as const;
