/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { DateRange } from './dateRange';
import type { IndexType } from './indexType';

export interface IQueryBuilder {
  readonly aliasesToIgnore?: readonly string[];
  readonly aliasesToSearch?: readonly string[];
  dateRangeToSearch?: DateRange;
  doNotIndexProperty?: string;
  ignoreDocumentsWithNoTemplate?: boolean;
  indexType?: IndexType;
  /** @nullable */
  startNodeId?: number | null;
}
