/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ISearchResultValues } from './iSearchResultValues';
import type { ISearchResultAllValues } from './iSearchResultAllValues';

export interface ISearchResult {
  /** @nullable */
  readonly id?: string | null;
  readonly score?: number;
  /** @nullable */
  readonly values?: ISearchResultValues;
  /** @nullable */
  readonly allValues?: ISearchResultAllValues;
}
