/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { NavigationItem } from './navigationItem';

export interface Locale {
  isDefault?: boolean;
  label?: string;
  isoCode?: string;
  defaultPath?: string;
  talentCommunityLink?: string;
  navigation?: NavigationItem[];
}
