/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { NavigationChild } from './navigationChild';

export interface NavigationItem {
  id?: string;
  title?: string;
  path?: string;
  children?: NavigationChild[];
}
