/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { SearchResult } from './searchResult';

export interface Paging {
  items?: SearchResult[];
  readonly hasItems?: boolean;
  pageSize?: number;
  readonly totalItems?: number;
  readonly totalPages?: number;
  currentPage?: number;
  readonly isFirstPage?: boolean;
  readonly isLastPage?: boolean;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  readonly resultStart?: number;
  readonly resultEnd?: number;
  readonly currentItems?: readonly SearchResult[];
}
