/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { ExamineSearchResults } from './examineSearchResults';
import type { Paging } from './paging';

export interface SearchApiResponse {
  searchResponse?: ExamineSearchResults;
  searchResultsPaged?: Paging;
  readonly hasSearchResults?: boolean;
  readonly hasSearchResponse?: boolean;
}
