/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Umbraco Delivery API
 * You can find out more about the Umbraco Delivery API in [the documentation](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api).
 * OpenAPI spec version: Latest
 */
import type { SearchResultValues } from './searchResultValues';
import type { SearchResultAllValues } from './searchResultAllValues';

export interface SearchResult {
  /** @nullable */
  id?: string | null;
  score?: number;
  /** @nullable */
  readonly values?: SearchResultValues;
  /** @nullable */
  readonly allValues?: SearchResultAllValues;
}
